export interface CategoryInputFormat {
  name: string;
  description: string;
}

export enum CategoryCodes {
  CATEGORY_CREATED = "CATEGORY_CREATED",
  CATEGORY_UPDATED = "CATEGORY_UPDATED",
  CATEGORY_DELETED = "CATEGORY_DELETED",
  CATEGORY_FOUND = "CATEGORY_FOUND",
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
  CATEGORY_ERROR = "CATEGORY_ERROR",
  CATEGORIES_FETCHED = "CATEGORIES_FETCHED",
}
