export interface CategoryInputFormat {
  name: string;
  description: string;
}

export enum CategoryCodes {
  CATEGORY_CREATED = "CATEGORY_CREATED",
  CATEGORY_UPDATED = "CATEGORY_UPDATED",
  CATEGORY_DELETED = "CATEGORY_DELETED",
  CATEGORY_FOUND = "CATEGORY_FOUND",
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
  CATEGORY_ERROR = "CATEGORY_ERROR",
  CATEGORIES_FETCHED = "CATEGORIES_FETCHED",
  CATEGORIES_NOT_FETCHED = "CATEGORIES_NOT_FETCHED",
  CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS",
  CATEGORIES_EMPTY = "CATEGORIES_EMPTY",
  CATEGORIES_NOT_EMPTY = "CATEGORIES_NOT_EMPTY",
  CATEGORY_INVALID_ID = "CATEGORY_INVALID_ID",
  CATEGORY_INVALID_FORMAT = "CATEGORY_INVALID_FORMAT",
}
